enqueue:
  default:
    transport:
      dsn: "rdkafka://"
      global:
        group.id: 'my_consumer_group'
        metadata.broker.list: '%env(KAFKA_BROKER_LIST)%'
      topic:
        auto.offset.reset: beginning
      commit_async: true
    client: ~