services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html:cached

  database:
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  test_database: # Тестовая БД
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_DB: test_symfony
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata:
  test_pgdata: